# Generated by Django 5.1.3 on 2024-11-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='avrBootcampCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('qr_url', models.URLField(blank=True, null=True)),
                ('cert_no', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('x_offset', models.IntegerField()),
                ('font_color', models.CharField(max_length=7)),
                ('font_size', models.IntegerField()),
                ('center', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('university_college', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('currently_pursuing', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('work_profile', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Working Professional', 'Working Professional'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
