# Generated by Django 5.1.4 on 2024-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecsysapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrbootcampcertificates',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avrbootcampcertificates',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
